mercari/tfnotify

terraform/parser.go
terraform/parser_test.go

When some error occurs, display all lines related to errors, not just only the title line of that error
We don't know the details as it is, so we have to press "details" tag. All logs should be hidden by "detail" tag. However, if it is just error lines, it should be displayed all.
NOW:

Display all error messages, not just one line

---

notifier/github/notify.go
terraform/template.go

By changing `tfnotify.yaml` as follows, make CI link available in template (e.g. github comment):
```diff
terraform:
plan:
template: |
-      {{ .Title }}
+      {{ .Title }} <sup>[CI link]( {{ .Link }} )</sup>
{{ .Message }}
{{if .Result}}
<pre><code> {{ .Result }}
```
In case of Circle CI, `{{ .Link }}` will be linked to the build page link such as https://circleci.com/gh/repo/org/1101
Make it easy to jump the CI page

Make CI link available in template

---

Makefile

- Fix reviewdog usage
- Change `-ci` flag to `-reporter` flag
Follow the latest usage

Update Makefile for reviewdog

---

Makefile
notifier/github/comment.go
notifier/github/comment_test.go

In GitHub's comment, duplicate comments should be limited to those matched only for titles.
Because `.Link` is changed every time if the template is set as follows, it's not recognized as duplicate comment.
```yaml
terraform:
plan:
template: |
{{ .Title }} <sup>[CI link]( {{ .Link }} )</sup>
```

Expand the condition as to whether it is a duplicate comment

---

terraform/template_test.go

Replace expected response format in test case to raw string literal.
IMO we can understand easily how the comment will rendered.
I'd like to fix https://github.com/mercari/tfnotify/issues/5.
Actually it's a bit hard to modify current test case now, for example, where I should insert `\n`.
Even if we want to write back quote in response, we can write as https://github.com/mercari/tfnotify/issues/5#issuecomment-384906718.

Use back quotes to represent expected response

---

README.md
config/config.go
main.go
notifier/github/client.go
notifier/github/client_test.go

Thank you for the great CLI tool! It would be awesome if you could take a look at this PR. 🙇
This PR adds support for GitHub Enterprise with `base_url` field and `GITHUB_BASE_URL` environment variable.
It seems that tfnotify doesn't support GitHub enterprise yet.

Add support for GitHub Enterprise

---

main.go
notifier/github/client.go
notifier/github/notify.go
notifier/slack/client.go
notifier/slack/notify.go

This PR enables to customize the title by `--title` option.
I'd like to customize the title used by notification.
We can specify the title in the config file like this:
```yaml
terraform:
plan:
template: |
{{ .Message }}
{{if .Result}}
<pre><code> {{ .Result }}
</pre></code>
{{end}}
<details><summary>Details (Click me)</summary>
<pre><code> {{ .Body }}
</pre></code></details>
```
But `getDuplicates()` in `notifier/github/comment.go` does not work well with this config.

Enable to customize title by --title option

---

.github/CODEOWNERS

Correct CODEOWNERS to refer both @dtan4 and @b4b4r07 
Following to [the current CODEOWNERS settings](https://github.com/mercari/tfnotify/blob/8bac913495b5b449ea012c999c7673f63f95f934/.github/CODEOWNERS), only @dtan4 is assigned as default reviewer.
To assign multiple members, they need to be written in the same line.
https://help.github.com/articles/about-codeowners/
```
*       @global-owner1 @global-owner2
```

Correct CODEOWNERS to refer @b4b4r07

---

Gopkg.lock
notifier/github/github.go

Use int64 for DeleteComment.
DeleteComment accepts int64 instead of int. The change happened few month ago.
https://github.com/google/go-github/pull/816/files#diff-31c1370935ebc7a4c8b8ee49256c38bcR111

Use int64 for DeleteComment

---

ci.go
ci_test.go

replace the envvar `CODEBUILD_AGENT_ENV_CODEBUILD_BUILD_URL` to `CODEBUILD_BUILD_URL`
It looks like that `CODEBUILD_AGENT_ENV_CODEBUILD_BUILD_URL` does not exist but `CODEBUILD_BUILD_URL` exists.

fix environment variable for CodeBuild

---

notifier/slack/client.go

Enable 2 env vars to configure slack channel id and bot name
Although the template example for slack in README looks like it is possible to configure channel id and bot name via env vars, these 2 env vars are actually not read.
https://github.com/mercari/tfnotify/blob/master/README.md#template-examples
( It might not be necessary to configure these via env vars. Please close this PR then. )

Enable slack env vars for channel id and bot name

---

README.md
config/config_test.go
example.tfnotify.yaml
terraform/template.go
terraform/template_test.go

Add an empty line after the `</summary>` tag in the templates.
Fix #5 in the templates.
and remove some blanks to clean up outputs (Refer to the screenshot below).

Update template examples to fix #5

---

ci.go
ci_test.go

fix codebuild-ci code to allow sourceVersion not to has prefix "pr/"
According to https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html, CODEBUILD_SOURCE_VERSION doesn't has prefix "pr/" when trigger is not pull request.
And If we use codebuild as CI and CODEBUILD_SOURCE_VERSION doesn't contain "pr/" , we encounter with error "strconv.Atoi: parsing "xxxxxxxxxxx": invalid syntax "  in tfnotify.
So tfnotify module should check whether sourceVersion has prefix "pr/" or not  and if it doesn't ,return ci and nil before func.strconv.Atoi.

fix codebuild-ci code to allow sourceVersion not to has prefix "pr/"

---

Makefile

Install the latest reviewdog binary directly instead of building a binary by ourselves using `go get`
Now an error is occurred in CI jobs during reviewdog installation.
https://github.com/mercari/tfnotify/pull/52#issuecomment-550692690
This might be fixed by upgrading dependencies, but it's not merged to master branch yet.
https://github.com/reviewdog/reviewdog/pulls
What we really want to do is just using reviewdog binary, not building reviewdog binary at all times. Instead of building binary and seeing error, just downloading a pre-built binary and use it is enough for us.
- [reviewdog/reviewdog - Installation](https://github.com/reviewdog/reviewdog#installation)

Install the latest reviewdog binary directly

---

README.md
config/config.go
config/config_test.go
example-with-destroy.tfnotify.yaml
main.go
notifier/github/client.go
notifier/github/notify.go
notifier/github/notify_test.go
terraform/parser.go
terraform/parser_test.go
terraform/template.go
terraform/template_test.go

This Pull Request enables tfnotify to comment warning message in addition to the normal plan message when the plan result contains destroy operation.
This feature supports both Terraform 0.11 or below and Terraform 0.12+. Currently, this feature is available on GitHub only.
Here is an example image. Since the plan result tells us Terraform will delete 12 resources, tfnotify warns it in addition to the normal plan comment.
This is an opt-in feature. When users add `when_destroy` configuration to their `tfnotify.yaml`, tfnotify will warn destroy operation. Without `when_destroy`, tfnotify will NOT warn it as well as the current version.
```yaml
terraform:
plan:
template: |
{{ .Title }} <sup>[CI link]( {{ .Link }} )</sup>
{{ .Message }}
{{if .Result}}
<pre><code> {{ .Result }}
</pre></code> …
```

Make it able to notify additionally when the plan result contains destroy operation

---

Makefile

Tidy up development dependencies
- Remove unused dependencies: `ghch`, `goxz`, and `ghr`
- They were replaced to GoReleaser, etc. https://github.com/mercari/tfnotify/commit/c6550df46069e323f0660e3565c43da9a860e231
- Add GoReleaser to dependencies
- GoReleaser is required by [release-go](https://github.com/b4b4r07/release-go)
We don't have to install unnecessary tools in every CI build. Additionally, some of them cause failure during installation.
https://github.com/mercari/tfnotify/pull/58#issuecomment-568978843

Tidy up development dependencies

---

README.md
config/config.go
config/config_test.go
example-use-raw-output.tfnotify.yaml
main.go
notifier/github/client.go
notifier/github/notify.go
terraform/template.go
terraform/template_test.go

Add a option `use_raw_output: true` to disable HTML escape for Terraform command output
```yaml
terraform:
use_raw_output: true # <<<-------
plan:
```
base configuration
```yaml
ci: circleci
notifier:
github:
terraform:
plan:
template: |
```
{{ .Body }}
```
```
Current tfnotify does HTML escape for all Terraform command outputs forcibly. For example, it replaces some characters to character references (e.g. `-/+` -> `-/&#43;`, `"` -> `&#34;`). However, when we use code blocks to render command outputs in Markdown, these character references are renders as they are. Therefore, the output in GitHub comment becomes weird for human.
We'd like to prevent HTML escape if necessary.

Add a option to disable HTML escape for Terraform command output in GitHub

---

README.md

Added an example for the `GITHUB_BASE_URL` for Github Enterprise
I discovered that the go client requires the base URL to include the `/api/v3` API endpoint for a privately hosted Github Enterprise account. Github Enterprise API endpoints follow the same pattern: `https://{{ hostname }}/api/v3/`

Add example for Github Enterprise base URL

---

ci.go
ci_test.go

This PR allows tfnotify work not only for pull request builds but also for branch builds.
There are two kind of build in Travis CI, branch build (triggered by push to a branch) and pull request build (triggered by push to a branch whose pull request exists).
Only pull request build have `TRAVIS_PULL_REQUEST` and `TRAVIS_PULL_REQUEST_SHA` variables, which tfnotify now uses to find the revisions of builds.
(ref: https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests)
This PR enables tfnotify to find the revisions of branch builds by refering `TRAVIS_COMMIT` variable, that represents the HEAD commit id of the current build. (ref: https://docs.travis-ci.com/user/environment-variables/#default-environment-variables)
For now, it is inconvenient to use tfnotify on Travis …

Support branch builds of Travis CI

---

notifier/github/commits.go
notifier/github/commits_test.go
notifier/github/github.go
notifier/github/github_test.go
notifier/github/notify.go
notifier/github/notify_test.go
notifier/slack/notify.go
notifier/slack/notify_test.go

Title
Right now, the apply result is commented on the commit just before the merge commit in master. If the PR merged in is not up to date with master, someone else's commit may be the commit right before the merge commit. This makes the apply result get commented on a completely unrelated commit instead of in the PR.

try parsing pr number to create apply result comment on merged pr

---

terraform/parser.go
terraform/parser_test.go

"diff a / name.tf b / name.tf" line is an extend optional header, so it may not appear in unified diff text.
we should use hunks (@@ -R +R @@ line) to detect errors, because they are parts of diff content.
terraform 0.11.x prints "diff a/name.tf b/name.tf" line, and tfnotify detect it.
https://github.com/hashicorp/hcl/blob/8cb6e5b959231cc1119e43259c4a608f9c51a241/hcl/fmtcmd/fmtcmd.go#L80
but, terraform 0.12.x does not print this line, so tfnotify can't detect fmt error.
https://github.com/hashicorp/terraform/commit/dc7f793be9f263de29b5220d9d7664fdca734659#diff-3ea9cc1590f58ec5fdbc03acc5f1c779R159-R166

fix that tfnotify fmt reports incorrect result

---

terraform/parser.go
terraform/parser_test.go

Update the `Fail` regex for `Apply`
As of terraform 0.12, [this line](https://github.com/hashicorp/terraform/blob/12bf5f6afec2a9dcc97357671fdfa9fb972884eb/backend/local/backend_apply.go#L163) has been removed and the regex no longer matches.
Since the new regex will also match terraform 0.11 results and older, there's no need to create a new regex.

update fail regex to handle new error text

---

README.md
ci.go
ci_test.go
config/config.go
main.go

Add support to GitHub Actions as CI service.
GitHub Actions creates GITHUB_TOKEN for a repository automatically. So, we don't have to create any GitHub accounts for tfnotify.

Add support to GitHub Actions

---

ci.go

Modify the CI link URL of Github action.
The link when using the environment variable GITHUB_RUN_ID is wrong.

Fix github actions link

---

README.md
terraform/template.go

Fix typo on README and GoDoc
Make the wording better

fix typo on readme and godoc

---

README.md
ci.go
ci_test.go
config/config.go
config/config_test.go
main.go

Add Google Cloud Build as a supported CI
When running `terraform` to operate GCP resources, using Google Cloud Build is a secure way because it doesn't need to create a Service Account key file.
---
I'm already using it in my personal project and it's working fine:

Support Google Cloud Build

---

.github/workflows/release.yml

Use Go 1.14 to build binaries for release, as well as testing.
We use Go 1.14 to run tests ([ref](https://github.com/mercari/tfnotify/blob/57494ec80c926a12967c8634226ef60e834b3dfd/.github/workflows/test.yml#L19)). However, GoReleaser still uses Go 1.13.
We should use the same Go version through the development/release pipeline.

Use Go 1.14 for release build

---

ci.go
ci_test.go

I have made changes to the link that will be used for `{{ .Link }}`.
To support Cloud Build private pools( Ref: [https://cloud.google.com/build/docs/private-pools/private-pools-overview](https://console.cloud.google.com/cloud-build/builds;region=global/45826848-4bb9-426e-b2fa-b6fc1585bc58?project=kouzoh-ms-terraform-dev)).
The Cloud Build build IDs are generated by regions. Thus, if we want to jump to the detail page of the build that ran on private pool, we need to specify the region by `;region=<region>`.
The non-private-pool will be `global` region. Currently, there are no regions specified which will jump to the default `global` region, that's why it's working. For private pools, the current link that tfnotify posts, it will not lead us to the detail. The GCP will return 404 page 🙏

Support regional (=private pool) Cloud Build

---

ci.go
ci_test.go

I have added `_` (understore) before the variable.
Because it doesn't follow the format. `REGION` is a custom substitution which the Cloud Build doesn't  build-in support.🙏 
> Substitutions must begin with an underscore (_) and use only uppercase-letters and numbers (respecting the regular expression _[A-Z0-9_]+)
Ref: https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values

Fix region user defined substitution format

---

README.md

As title.
Context: https://github.com/mercari/tfnotify/issues/102
I added a variable lookup in the previous https://github.com/mercari/tfnotify/pull/101 but forgot to update the readme 🙏  
(The variable was renamed later https://github.com/mercari/tfnotify/pull/103)

Add `_REGION` substitute to readme Cloud  Build section

---

terraform/parser.go
terraform/parser_test.go

I have supported Terraform version `>= 0.15`
For https://github.com/mercari/tfnotify/issues/104.
Because `tfnotify` can't parse failure messages from `0.15`, we can't use it. Thus, this PR aims to support it.

Support Terraform `0.15` or later

---

notifier/slack/notify.go

Link template variable can be used for notifications to Slack.
I would like to jump to CI from a notified Slack message.

Add CI url as Link template value for slack notification

---

terraform/parser.go
terraform/parser_test.go

Because the Terraform (https://github.com/hashicorp/terraform/blob/f9603d3b14f367f81d8fb7fd3e22c8c78fc4e436/internal/command/format/diagnostic.go#L54-L65) used the `│`  (`U+2502` Box Drawing Light Vertical Unicode Character) instead of `|`U+007C` vertical bar )🙇

Fix error parse regex char for Terraform >= 0.15

---

terraform/parser.go
terraform/parser_test.go

For https://github.com/mercari/tfnotify/issues/108
The `tfnotify` runs into error where there are only changes on the `outputs`.

Support Terraform `>= 0.15` or later plan output only changes

---

notifier/github/client.go
notifier/github/client_test.go

If the token with `$` are configured, lookup the environment variable.
For https://github.com/mercari/tfnotify/issues/111.
In current implementation, the `tfnotify` only supports `GITHUB_TOKEN` and users can't specify a environment variable of their own.

Support custom GitHub token environment variable name

---

notifier/github/notify.go

refactor: Fix typo

---

notifier/github/notify.go
notifier/github/notify_test.go

I shorten too long results commented to GitHub. 
When you try to comment too long message, GitHub API will return error, and nothing is commented to PR.
```
POST https://api.github.com/repos/<owner>/<repo>/issues/<pr number>/comments: 422 Validation Failed [{Resource:IssueComment Field:data Code:unprocessable Message:Body is too long (maximum is 65536 characters)}]
```

shorten too long github comment

---

terraform/parser.go
terraform/template.go
terraform/template_test.go

Instead of just printing:
`"There is diff in your .tf file (need to be formatted)"`
I'm sending the full body:
We want to let the user know what the problem was.

feat: Support body from fmt command
